<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

**Exercise 1**

| term        |  description   |
|---|  ---   |
| subsetting  | to select              |
| indexing    | selecting 1 element              |
| slicing     | selecting a range of elements              |
| masking     | representing elements as True/False             |

**Exercise 2**

In [36]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numarray = np_array_2d[:,0]

remainder = []
for i in numarray.astype(int):
    rem = i%2
    remainder.append(rem)

remarray = np.array(remainder)
mask = remarray != 0

for i in range(len(mask)):
    if mask[i]:
        print(np_array_2d[i, 1])

A
C
E
G
I


**Exercise 3**

In [42]:
import numpy as np

nparray = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

array = np.array(nparray)

array[array < 50] = -1
array[array > 50] = 1
array[array == 50] = 0

print(array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
